{% set name = "mediafile" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mediafile-{{ version }}.tar.gz
  sha256: de71063e1bffe9733d6ccad526ea7dac8a9ce760105827f81ab0cb034c729a6d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core >=2,<4
  run:
    - mutagen >=1.46
    - python >={{ python_min }}
    - filetype >=1.2.0
    
test:
  imports:
    - mediafile
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  dev_url: https://github.com/beetbox/mediafile
  summary: Handles low-level interfacing for files' tags.
  license: MIT
  license_file: LICENSE
  doc_url: https://mediafile.readthedocs.io/
  home: https://github.com/beetbox/mediafile
  description: |
    MediaFile is a simple interface to the metadata tags for many audio file formats. It wraps Mutagen, a high-quality library for low-level tag manipulation, with a high-level, format-independent interface for a common set of tags.

extra:
  recipe-maintainers:
    - HeavyTony2
